project_id = "issxzqnozaxkqweifkmq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.health-chat]
verify_jwt = true

[functions.health-predictions]
verify_jwt = true

[functions.iot-webhook]
verify_jwt = false

[functions.create-video-room]
verify_jwt = true

[functions.digital-twin-simulation]
verify_jwt = true

[functions.xai-predictions]
verify_jwt = false